### ISSUE TITLE
Fix Pillow 3.0+ support - changed api

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [Joacchim/Comix#6]
Here will be error: https://github.com/Joacchim/Comix/blob/master/src/image.py#L226
```
NotImplementedError: tostring() has been removed. Please call tobytes() instead.
```

You can fix it like I did in my fork: https://github.com/sergey-dryabzhinsky/Comix/commit/1c4994cbf72c9733980ab65ce84063f4dd8ffa41#diff-1ab5625ca08d19a6bdfaad7d239ca6f5

**Comment by DavidPineauScality** [comment]
Hello,

sorry for not answering to this earlier (nor to the other issue that is soo old, mea maxima culpa..)

I'm thinking that the easiest way would be to pull the changes from your fork, getting all the fixes merged in there. Would that be ok for you ?

**Comment by sergey-dryabzhinsky** [comment]
That will be ok.
But beware of changes - changelog, links to repository, etc. - not compatible with your main code.

**Comment by DavidPineauScality** [comment]
May I ask your review on such update then ?
I'm of the mind to keep the Changelog as-is, and create multiple tags when merging (thus shamelessly "simulating" the past releases made on your side), so that it matches the history of your fork; You actually did have more maintenance work on your side than this fork of the original Comix code.

**Comment by sergey-dryabzhinsky** [comment]
Ok, I can do that.

**Comment by sergey-dryabzhinsky** [comment]
Done
